var networkInfo = {
  "bitcoinNetworkInfo": {
    'name': 'Bitcoin Protocol',
    'displayName': 'Bitcoin',
    'chainId': 0,
    'ticker': 'BITCOIN',
    'description': 'The first blockchain network',
    'derivationPath': "m/84'/0'/0'/0/0",
    'isTestnet': false,
    'logoUrl': 'https://beepo.blob.core.windows.net/logos/Bitcoin.png',
    'nameoncoinmarketcap': 'Bitcoin',
  },

  // solanaNetworkInfo: {
  //  'name': 'Solana Mainnet',
  //   'displayName': 'Solana',
  //   'chainId': 501,
  //   'ticker': 'SOL',
  //   'description': 'The first non-EVM based blockchain network aside bitcoin',
  //   'derivationPath': "m/44'/501'/0'/0",
  //   'isTestnet': false,
  //   'logoUrl': 'https://beepo.blob.core.windows.net/logos/Solana.png',
  //   'nameoncoinmarketcap': 'Solana',
  // },

  'networksInfo': {
    1: {
      'name': 'Ethereum Mainnet',
      'displayName': 'Ethereum',
      'chainId': 1,
      'ticker': 'ETH',
      'description': 'The first EVM based blockchain network',
      'derivationPath': "m/44'/60'/0'/0",
      'isTestnet': false,
      'logoUrl': 'https://beepo.blob.core.windows.net/logos/Ethereum.png',
      'nameoncoinmarketcap': 'Ethereum',
    },
    56: {
      'name': 'Binance Smartchain Mainnet',
      'displayName': 'Binance Smartchain',
      'chainId': 56,
      'ticker': 'BNB',
      'description': 'The centralized  EVM based smart blockchain network with low transaction fees',
      'derivationPath': "m/44'/60'/0'/0",
      'isTestNet': false,
      'logoUrl': 'https://beepo.blob.core.windows.net/logos/Smartchain.png',
      'nameoncoinmarketcap': 'BNB',
    },
    'busd': {
      'name': 'Binance Smartchain Mainnet',
      'displayName': 'Binance USD',
      "rpc": {'https': 'https://bsc-dataseed.binance.org/', 'testnet': 'https://data-seed-prebsc-1-s1.binance.org:8545/', 'wss': ""},
      'chainId': 56,
      "address": '0xeD24FC36d5Ee211Ea25A80239Fb8C4Cfd80f12Ee',
      'ticker': 'BUSD',
      'description': 'The centralized  EVM based smart blockchain network with low transaction fees',
      'derivationPath': "m/44'/60'/0'/0",
      'isTestNet': false,
      'logoUrl': 'https://beepo.blob.core.windows.net/logos/Smartchain.png',
      'nameoncoinmarketcap': 'BNB',
    },
    137: {
      'name': 'Polygon Mainnet',
      'displayName': 'Polygon',
      'chainId': 137,
      'ticker': 'MATIC',
      'description': 'This is the Polygon matic description',
      'derivationPath': "m/44'/60'/0'/0",
      'isTestNet': false,
      'logoUrl': 'https://beepo.blob.core.windows.net/logos/Polygon.png',
      'nameoncoinmarketcap': 'Polygon',
    },
    42220: {
      'name': 'Celo Mainnet',
      'displayName': 'Celo',
      'chainId': 42220,
      'ticker': 'CELO',
      'description': 'The Celo network',
      'derivationPath': "m/44'/52752'/0'/0",
      'isTestNet': false,
      'logoUrl': 'https://beepo.blob.core.windows.net/logos/Celo.png',
      'nameoncoinmarketcap': 'Celo',
    },
    256256: {
      'name': 'Caduceus Mainnet',
      'displayName': 'Caduceus',
      'chainId': 256256,
      'ticker': 'CMP',
      'description': 'The Caduceus network',
      'derivationPath': "m/44'/60'/0'/0",
      'isTestNet': false,
      'logoUrl': 'https://beepo.blob.core.windows.net/logos/Caduceus.png',
      'nameoncoinmarketcap': 'Caduceus',
    },
    32520: {
      'name': 'Bitgert Mainnet',
      'displayName': 'Bitgert',
      'chainId': 32520,
      'ticker': 'Brise',
      'description': 'The Bitgert network',
      'derivationPath': "m/44'/60'/0'/0",
      'isTestNet': false,
      'logoUrl': 'https://beepoassets.s3.amazonaws.com/bitgert.jpeg',
      'nameoncoinmarketcap': 'Bitgert',
    },
    'Bitgert': {
      'name': 'Bitgert Mainnet',
      'displayName': 'Bitgert',
      'chainId': 32520,
      'ticker': 'Brise',
      "rpc": {
        'https': "https://rpc.icecreamswap.com",
        'testnet': "https://rpc.icecreamswap.com",
        'wss': "",
      },
      'description': 'The Bitgert network',
      'derivationPath': "m/44'/60'/0'/0",
      "address": '0x8FFf93E810a2eDaaFc326eDEE51071DA9d398E83',
      'isTestNet': false,
      'logoUrl': 'https://beepoassets.s3.amazonaws.com/bitgert.jpeg',
      'nameoncoinmarketcap': 'Bitgert',
    },
    "beepo": {
      'name': 'Beepo',
      'displayName': 'Beepo',
      "address": '0x87c6ccc98f62d2aa4bd072610b8064991bf81d83',
      'ticker': 'BEEP',
      'chainId': 56,
      "rpc": {'https': 'https://bsc-dataseed.binance.org/', 'testnet': 'https://data-seed-prebsc-1-s1.binance.org:8545/', 'wss': ""},
      'description': 'The Beepo network',
      'derivationPath': "m/44'/60'/0'/0",
      'isTestNet': false,
      'logoUrl': 'https://beepoassets.s3.amazonaws.com/beepo.jpeg',
      'nameoncoinmarketcap': 'beepo',
    },
  },

  'rpcUrls': {
    1: {
      'https': 'https://eth-rpc.gateway.pokt.network',
      'testnet': 'https://goerli.infura.io/v3/5fd05c9976d44bb7a6e849317e9ad9c0',
      'wss': '',
    },
    5: {
      'https': 'https://goerli.infura.io/v3/5fd05c9976d44bb7a6e849317e9ad9c0',
      'testnet': 'https://goerli.infura.io/v3/5fd05c9976d44bb7a6e849317e9ad9c0',
      'wss': '',
    },
    56: {'https': 'https://bsc-dataseed.binance.org/', 'testnet': 'https://data-seed-prebsc-1-s1.binance.org:8545/', 'wss': ""},
    42220: {'https': "https://forno.celo.org", 'testnet': "https://alfajores-forno.celo-testnet.org", 'wss': "wss://forno.celo.org/ws"},
    137: {'https': "https://polygon-rpc.com", 'testnet': "https://rpc-mumbai.maticvigil.com", 'wss': ""},
    256256: {
      'https': "https://mainnet.block.caduceus.foundation",
      'testnet': "https://galaxy.block.caduceus.foundation",
      'wss': "",
    },
    32520: {
      'https': "https://rpc.icecreamswap.com",
      'testnet': "https://rpc.icecreamswap.com",
      'wss': "",
    }
  },

  'contractAddresses': {
    5: {'contractAddress': "0x627118a4fB747016911e5cDA82e2E77C531e8206"},
    1: {
      'contractAddress': "0x2170ed0880ac9a755fd29b2688956bd959f933f8",
    },
    56: {
      'contractAddress': "0x242a1ff6ee06f2131b7924cacb74c7f9e3a5edc9",
    },
    137: {'contractAddress': "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619"},
    42220: {'contractAddress': "0xc03f9c16aebad87379c0036390317a1ebde59081"},
    256256: {'contractAddress': "0x07686C0BA221f2427BB95B88ee8A94E784022ed0"}
  },

  'supportedNetworkIds': [1, 5, 56, 42220, 137, 256256, 32520, "bitcoin", "beepo"],

  'supportedNetworkNames': ['bitcoin', 'bitgert', 'ethereum', 'smartchainMainnet', 'smartchainTestnet', 'celo', 'polygon', 'caduceus', 'beepo'],

  'networkNameMap': {
    'ethereumMainnet': 1,
    'smartchainMainnet': 56,
    'celo': 42220,
    'celoTestnet': 4220,
    'polygon': 137,
    'caduceusMainnet': 256256,
    'bitgert': 32520
  },

  'explorerUrls': {
    1: "https://etherscan.io",
    5: "https://goerli.etherscan.io",
    56: "https://bscscan.com",
    42220: "https://explorer.celo.org/mainnet",
    137: "https://polygonscan.com",
    256256: "https://mainnet.scan.caduceus.foundation",
    32520: "https://explorer.bitgert.com",
  },
};
